INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (1,'Avellaneda');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (2,'Bahia Blanca');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (3,'Banfield');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (4,'CABA');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (5,'Cordoba');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (6,'Fcio Varela');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (7,'Junin');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (8,'La Plata');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (9,'Lanus');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (10,'Mar del Plata');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (11,'Mendoza');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (12,'Misiones');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (13,'Paraná');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (14,'Quilmes');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (15,'Rafaela');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (16,'Rosario');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (17,'Saavedra');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (18,'San Juan');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (19,'Santa Fe');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (20,'Santiago del Estero');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (21,'Sarandi');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (22,'Temperley');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (23,'Tucuman');
INSERT INTO `locaciones` (`id_locacion`,`locacion`) VALUES (24,'Victoria');