INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (1,'Aldosivi',10);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (2,'Argentinos',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (3,'Arsenal',21);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (4,'Atl Rafaela',15);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (5,'Atl Tucuman',23);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (6,'Banfield',3);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (7,'Barracas Central',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (8,'Belgrano',5);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (9,'Boca Juniors',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (10,'Central Cba (SdE)',20);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (11,'Chacarita',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (12,'Colon',19);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (13,'Crucero (M)',12);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (14,'Def y Justicia',6);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (15,'Estudiantes (LP)',8);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (16,'Gimnasia (LP)',8);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (17,'Godoy Cruz',11);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (18,'Huracan',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (19,'Independiente',1);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (20,'Lanus',9);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (21,'Newells',16);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (22,'Nueva Chicago',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (23,'Olimpo',2);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (24,'Patronato',13);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (25,'Platense',17);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (26,'Quilmes',14);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (27,'Racing Club',1);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (28,'River Plate',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (29,'Rosario Central',16);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (30,'San Lorenzo',4);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (31,'San Martin (SJ)',18);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (32,'San Martin (T)',23);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (33,'Sarmiento (J)',7);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (34,'Talleres (C)',5);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (35,'Temperley',22);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (36,'Tigre',24);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (37,'Union',19);
INSERT INTO `equipos` (`id_equipo`,`equipo`,`id_locacion`) VALUES (38,'Velez',4);
